### ISSUE TITLE
Erro com produtos com Estrutura vazias / Chamada de Modulo

### ISSUE THREAD

**Issue by crodriguesmg** [AlexandreBellas/bling-erp-api-php#20]
Quando um produto está sendo solicitado via "find" se o nó do array estrutura estiver com os dados vazio ele retorna erro, ou seja, seria como um KIT ou combo, se não tiver dados ele retorna erro no Entities/Produtos/Enum -> Situacao.php , TipoEstoque.php, lancamentoEstoque.php

Situacao.php ->Adicionar o case EXCLUIDO = 'E';
TipoEstoque.php e lancamentoEstoque.php -> case UNDEFINED = ''; // Caso para tratar valores vazios

definir esses case resolveram o problema me meu codigo

Outro problema está no arquivo
Bling.php -> o modulo Canais de venda não foi adicionado.

Adicionar a seguinte linha na função __get
'CanaisDeVenda' => $this->getModule(CanaisDeVenda::class),

**Comment by AlexandreBellas** [comment]
Obrigado pelo feedback! Até este fim de semana estarei implementando as correções que você pontuou.
Caso você precise das correções mais cedo, você pode abrir um PR com elas, o que você preferir. :smile:

**Comment by crodriguesmg** [comment]
Opa boa tarde.
Perfeito meu amigo, baixei aqui e deu certo essa atualização.

Eu estou usando praticamente toda a biblioteca em um sistema interno da
empresa,
eu estou verificando estrutura e chegou outro erro

Quando consulto uma produto filho que está dentro da estrutura de um outro
produto tenho esse seguinte errro
Desabilitei essas três variaveis e deu certo, mas uma vez o problema está
quando vem vazio agora o item componente:[] da estrutura
public string $ordem,
public Id $anexo,
public Id $anexoVinculo,
"success": false,
"error": "Could not parse property \"ordem\" of type \"string\".",
"message": "Error on Data"
}
<?php

namespace AleBatistella\BlingErpApi\Entities\Produtos\Schema\Find;

use AleBatistella\BlingErpApi\Entities\Shared\BaseResponseObject;
use AleBatistella\BlingErpApi\Entities\Shared\DTO\Schema\Id;

readonly final class FindResponseDataMidiaImagensInternas extends
BaseResponseObject
{
/**
* Constrói o objeto.
*
* @param string $linkMiniatura
* @param string $validade
* @param string $ordem
* @param Id $anexo
* @param Id $anexoVinculo
*/
public function __construct(
public string $linkMiniatura,
public string $validade,
public string $ordem,
public Id $anexo,
public Id $anexoVinculo,
) {}
}

**Comment by AlexandreBellas** [comment]
Fico feliz que a biblioteca está sendo útil para a sua empresa! :smile: 

Vou dar uma olhada neste último bug esta semana. Te dou um feedback assim que possível.
Uma pena que a documentação do Bling não é tão clara quanto à possibilidade de vir _string_ vazia na resposta. :melting_face:

**Comment by AlexandreBellas** [comment]
Pelo o que vi no código, o atributo `ordem` de um objeto do _array_ `midia->imagens->internas` não está vindo como parte do `$attributes` de `BaseResponseObject`, representando que a API não está retornando o valor de `ordem` preenchido. Ou seja, ele pode ser `null`.

Vou deixá-lo _nullable_ para resolver seu problema. Uma pena que não podemos confiar tanto assim na documentação. rs

![image](https://github.com/user-attachments/assets/f00cbb76-8afa-4b87-9243-c74957c1520c)

**Comment by AlexandreBellas** [comment]
Lancei a [release v1.14.2](https://github.com/AlexandreBellas/bling-erp-api-php/releases/tag/v1.14.2) que torna os atributos _nullable_. Faça um teste com a nova versão e veja se isso corrige o seu caso. :pray:
